### ISSUE TITLE
Version 1.0a1 not installing via pip and requirements

### ISSUE THREAD

**Issue by isaquefms** [jazzband/django-auditlog#332]
Guys, i needed to update `django-auditlog` to version `1.0a1` in my project to update the dependency `python-dateutil`.

When i try to install the package via requirements the pip returns the following message: `Could not find a version that satisfies the requirement django-auditlog==1.0a1`.

Is this normal, maybe because the version is under alpha release ?

When a try to manually install using cmd (`pip install django-auditlog==1.0a1`) everything works fine.

In requirements:
`django-auditlog==1.0a1`

Obs: The error occurs when ansible executes the command.

**Comment by Linkid** [comment]
Which command are you using ?

**Comment by isaquefms** [comment]
`pip install -r requirements.txt`

**Comment by Linkid** [comment]
Maybe your ansible playbook does not accept pre-release, because the command line you are using is working.
Here are some questions that can help:
- which version of python are you using ?
- which command does your ansible playbook run ?
- did you try to double quote `django-auditlog==1.0a1` ?
- what is the content of your `requirements.txt` file ?
