### ISSUE TITLE
Can't remove any auditlogged objects through the admin

### ISSUE THREAD

**Issue by aleh-rymasheuski** [jazzband/django-auditlog#493]
As @madomdy [commented](https://github.com/jazzband/django-auditlog/pull/449#issuecomment-1370397139) in a related pull request, they are unable to remove objects of any model connected to the audit log.

![screenshot](https://user-images.githubusercontent.com/5181983/210469079-1eda4086-90cb-4334-a937-112d513234c4.png)

Possibly minimal app to reproduce the issue (I haven't tested it):
```python
# model.py
from auditlog.models import AuditlogHistoryField
from django.db import models


class MyModel(models.Model):
    history = AuditlogHistoryField()    

# admin.py
from django.contrib import admin

from .models import MyModel


admin.site.register(MyModel)
```

Instances of `MyModel` can't be removed through the admin because of `AuditlogHistoryField` and the delete permissions retracted in #449.

Workaround: pass `delete_related=False` to `AuditlogHistoryField` (`history = AuditlogHistoryField(delete_related=False)`).

**Comment by hramezani** [comment]
I also couldn't reproduce the problem

**Comment by ilhan** [comment]
Seems to be related to AuditlogHistoryField, I added `delete_related=False` to AuditlogHistoryField(delete_related=False) as a fix, haven't investigated further.

**Comment by alieh-rymasheuski** [comment]
Thanks @ilhan, that was the missing piece of the puzzle. I'll update the description of the issue.

**Comment by christianwgd** [comment]
Wouldn't it be much more flexible, if we can not only set this to True or False but have the same values like in normal referential integrity (SET_NULL, CASCADE, PROTECT)?

**Comment by alieh-rymasheuski** [comment]
@christianwgd, your comment made me investigate this flag more deeply. I had the impression that `delete_related` was a standard parameter of `GenericRelation` and I was about to say so. I was wrong.

At the first glance it makes sense to support `on_delete` keyword. But on the other hand, how valuable `SET_NULL` (and the rest of the family of `SET` options) may be for the audit log table?

@hramezani, if we change `delete_related` to be `False` by default (or make an equivalent change through the potential new `on_delete` parameter), this will be a breaking change. We should include it in the 3.0 release.

**Comment by christianwgd** [comment]
@alieh-rymasheuski, I thought about the SET_NULL option and found it useful, if you want to see, that someone has deleted an object and maybe recall the history of that. Yes, maybe it's not the most used one, but as I understood the "delete_related" option, it would exactly be like SET_NULL if set to False (delete object and keep the audit log). And the "PROTECT" value would exactly do, what "delete_related" would to, if set to True. What I am missing is CASCADE, delete the object and delete all connected audit log items.
But anyway thanks for investigating...

**Comment by alieh-rymasheuski** [comment]
Effect of builtin `on_delete` options as compared to `delete_related`.

| on_delete   | delete_related | comment                                                                                                                           |
|-------------|----------------|-----------------------------------------------------------------------------------------------------------------------------------|
| CASCADE     | True           | This is the default behavior of `GenericRelation`. It was broken in #449 and now the default behavior is similar to `PROTECT`     |
| DO_NOTHING  | False          | As for me, this is the only correct behavior ;)                                                                                   |
| PROTECT     |                | May make sense if we don't track `create` actions, otherwise this option will disable deletion altogether                            |
| RESTRICT    |                | Can't think of a scenario when it will be different from `PROTECT`                                                                |
| SET         |                | May be used to mark auditlog of deleted objects, but I'd not recommend mangling auditlog like that                                |
| SET_NULL    |                | Same reasoning as for `SET`. Additionally, this will fail if used together with `pk_indexable=False` as `object_pk` is not nullable |
| SET_DEFAULT |                | Given that `object_id` and `object_pk` have no default, this will have no effect                                                                          |

**Comment by christianwgd** [comment]
Your'e right. I would reduce my requirement to have a third value beyond True and False. As I understood the fix in #449 "changes" the delete_related value from "PROTECT" to "CASCADE" and for me the new behaviour of the True value is all I need, but I could imagine cases where I would like to set it to the old behaviour.

**Comment by hramezani** [comment]
@alieh-rymasheuski I think we need to revert https://github.com/jazzband/django-auditlog/pull/449. 
I've created (V2 branch)[https://github.com/jazzband/django-auditlog/tree/v2] on top of `2.2.1`.
Could you please create a PR base on `V2 branch` and revert it? Then I will release `2.3`

**Comment by hramezani** [comment]
[django-auditlog 2.2.2](https://pypi.org/project/django-auditlog/) has been released!

**Comment by suricactus** [comment]
Hey @hramezani , can you please update the [CHANGELOG.md](https://github.com/jazzband/django-auditlog/blob/master/CHANGELOG.md) file, so the 2.2.2 release notes are present in their own section.

**Comment by hramezani** [comment]
Hey @suricactus, I've created a PR to add it https://github.com/jazzband/django-auditlog/pull/510
