### ISSUE TITLE
Multiple updates are not supported

### ISSUE THREAD

**Issue by dalvgui** [jazzband/django-auditlog#515]
Hi all!

I don't know if you haven't noticed it. Multiple updates are not supported. Maybe it's a to-do feature/pending change and not a bug.

Example of multiple updates:
`Entry.objects.filter(pub_date__year=2010).update(comments_on=False)`

example extracted from [https://docs.djangoproject.com/en/4.1/ref/models/querysets/#update](https://docs.djangoproject.com/en/4.1/ref/models/querysets/#update) 

These updates are not detected, and they do not generate new LogEntries.

Let me know more about this, Thanks!

**Comment by alieh-rymasheuski** [comment]
@dalvgui, this is expected. `queryset.update(comments_on=False)` emits a single SQL statement `UPDATE something_entry SET comments_on = false WHERE extract(year from pub_date) = 2010`, bypassing the ORM layer altogether. Log entry generation is tied to signals emitted by ORM operations and is not triggered by such bulk operations.

In case if you need a particular operation to be reflected in the auditlog, just rewrite the queryset operation as a Python loop:
```python
for entry in Entry.objects.filter(pub_date__year=2010:
    entry.comments_on = False
    entry.save()
```

Note that this approach is much less performant.

It is possible to complement a bulk update operation with a bulk create of auditlog entries. However, I don't think it's viable to bake this option into the auditlog package because there are edge cases which will either reduce the performance of bulk operations by default, or will require non-trivial logic, such as:
- `LogEntry.changes` needs to know the old value of the field on every updated object;
- `LogEntry.object_repr` requires calling Python code on an instantiated ORM object;
- `LogEntry.serialized_data` (when enabled) requires loading full objects into the ORM too.
